#define DEBOUNCE 5
#define TAPPING_TERM 185
#define HOLD_ON_OTHER_KEY_PRESS

#define NO_ACTION_ONESHOT
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define BACKLIGHT_DEFAULT_ON false
#define BACKLIGHT_DEFAULT_BREATHING false
