#define DEBOUNCE 5
#define TAPPING_TERM 185
#define HOLD_ON_OTHER_KEY_PRESS

#define NO_ACTION_ONESHOT

#define BACKLIGHT_DEFAULT_ON false
#define BACKLIGHT_DEFAULT_BREATHING false
#define COMBO_TERM 15
