BOOTMAGIC_ENABLED = no
COMMAND_ENABLED   = no
MOUSEKEY_ENABLED  = yes
EXTRAKEY_ENABLE   = yes # Audio control and System control
CONSOLE_ENABLE    = no  # Console for debug
SLEEP_LED_ENABLE  = no  # Breathing sleep LED during USB suspend
NKRO_ENABLE       = no  # USB Nkey Rollover
BACKLIGHT_ENABLE  = no
VISUALIZER_ENABLE = no
